on: push
name: Deploy website
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Get latest code
          uses: actions/checkout@v4

        - name: Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: ${{ secrets.ftp_url }}
            server-dir: "public_html/"
            username: ${{ secrets.ftp_username }}
            password: ${{ secrets.ftp_password }}